---
title: "plot VAD param performance"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load/Install Packages
ipak <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg)) 
    install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE)
}
packages <- c('magrittr', 'data.table',  'ggplot2','tidyverse', 'dplyr','tidyr','lemon')
ipak(packages)

```

Session-wise
```{r}
results <- read_csv('/Users/roso8920/Dropbox (Emotive Computing)/iSAT/AudioPrepro/results/VAD/deepSample2/sesswise.csv') 
results_avg <- read_csv('/Users/roso8920/Dropbox (Emotive Computing)/iSAT/AudioPrepro/results/VAD/deepSample2/averaged_over_sess.csv') 
results_avg$agg <- factor(results_avg$agg)
results_avg$win_length <- factor(results_avg$win_length)

# average by agg
ggplot() +
  # geom_line(aes(group=sessname))+
  geom_line(data=results_avg, aes(x=frame_length, y = F1, color=agg, group=agg))+
  facet_rep_grid(win_length~min_seg_dur)+
  scale_color_brewer(palette="Dark2")+
  ggtitle('F1 By min dur & window length')+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank())
ggsave('./results/VAD/by_F1.png', width=6, height=6)

ggplot() +
  # geom_line(aes(group=sessname))+
  geom_line(data=results_avg, aes(x=frame_length, y = precision_prop, color=agg, group=agg))+
  facet_rep_grid(win_length~min_seg_dur,  labeller = labeller(min_seg_dur=label_both, win_length=label_both))+
  scale_color_brewer(palette="Dark2")+
  ggtitle('Precision By min dur & window length')+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank())
ggsave('./results/VAD/by_precision.png', width=6, height=6)

ggplot() +
  # geom_line(aes(group=sessname))+
  geom_line(data=results_avg, aes(x=frame_length, y = recall_prop, color=agg, group=agg))+
  facet_rep_grid(win_length~min_seg_dur)+
  scale_color_brewer(palette="Dark2")+
  ggtitle('Recall By min dur & window length')+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank())
ggsave('./results/VAD/by_recall.png', width=6, height=6)

```

ECAPA
```{r}
results <- read_csv('/Users/roso8920/Dropbox (Emotive Computing)/iSAT/AudioPrepro/results/speaker_verification/deepSample2_EvT_10s_realEnrollment/deepSample2_EvT_10s_realEnrollment_ecapa_results.csv') %>% 
  pivot_longer(-c(frame_dur_s, split), names_to='metric', values_to = 'value') %>% filter(metric %in% c('accuracy','precision','recall','train_EER'))

results_avg <- read_csv('/Users/roso8920/Dropbox (Emotive Computing)/iSAT/AudioPrepro/results/speaker_verification/deepSample2_EvT_10s_realEnrollment/deepSample2_EvT_10s_realEnrollment_ecapa_results_by_group.csv')%>% 
  pivot_longer(-c(frame_dur_s), names_to='metric', values_to = 'value') %>% filter(metric %in% c('accuracy','precision','recall','train_EER'))

ggplot(data=results,aes(x=frame_dur_s, y = value)) +
  geom_line(aes(group=split))+facet_wrap(~metric)+
  geom_line(data=results_avg, aes(x=frame_dur_s, y = value, color="mean"))+
  ggtitle('ECAPA')



```


```{r}
results <- read_csv('/Users/roso8920/Dropbox (Emotive Computing)/iSAT/AudioPrepro/results/speaker_verification/deepSample2_EvT_10s_realEnrollment/deepSample2_EvT_10s_realEnrollment_ecapa_results.csv')

ggplot(results, aes(x=frame_dur_s, y = accuracy)) +geom_line()

ggplot(results, aes(x=frame_dur_s, y = precision)) +geom_line()

ggplot(results, aes(x=frame_dur_s, y = recall)) +geom_line()

ggplot(results, aes(x=frame_dur_s, y = train_EER)) +geom_line()


```

Stats on the tests